#!/usr/bin/env python3
"""
Write the three output files for a classified JD.

Usage (pipe Claude's JSON output directly):
    echo '<json>' | python3 write_jd.py

Input (stdin): JSON object with all classification fields plus:
  - jd_text: full verbatim JD text
  - source_url: original URL

Output files written to jd_data/{jd_id}/:
  - jd_archive.md   — raw verbatim JD text
  - jd.md           — formatted JD + Layer B prose analysis
  - {jd_id}.json    — classification record (source_url + evidence included)
"""

import json
import sys
from pathlib import Path

JD_DATA_DIR = Path(__file__).parent / "jd_data"

BOOL_FIELDS = [
    "has_dbt", "has_spark", "has_python", "has_sql",
    "has_airflow", "has_dagster", "has_prefect",
    "has_snowflake", "has_databricks", "has_bigquery", "has_redshift", "has_duckdb",
    "has_kafka", "has_terraform",
    "has_looker", "has_tableau", "has_power_bi",
    "has_great_expectations", "has_soda",
]

LAYER_B_FIELDS = [
    "velocity_vs_rigour", "domain_risk", "collaboration_width", "data_team_maturity",
    "jd_authorship", "stakeholder_orientation", "autonomy_level",
    "greenfield_vs_fix", "urgency", "language_gate_type", "interview_stages",
    "ats_platform", "ats_job_id",
]

JSON_FIELD_ORDER = [
    "jd_id", "company", "role", "job_location", "seniority", "role_type",
    "salary_min", "salary_max", "salary_currency",
    "jd_authorship", "stakeholder_orientation", "autonomy_level",
    "greenfield_vs_fix", "velocity_vs_rigour", "domain_risk",
    "collaboration_width", "data_team_maturity", "urgency",
    "language_gate_type", "language_gate_languages",
    "interview_stages", "ats_platform", "ats_job_id",
] + BOOL_FIELDS + ["source_url", "evidence"]


def fmt_language_gate(data: dict, evidence: dict) -> str:
    gate_type = data.get("language_gate_type", "none")
    if gate_type == "none":
        return f"{gate_type} — Not stated in JD."
    # Use verbatim evidence quote when a gate exists
    quote = evidence.get("language_gate", "")
    if quote and quote != "Not stated in JD":
        return f'{gate_type} — "{quote}"'
    # Fallback to language list
    langs = data.get("language_gate_languages") or []
    langs_str = ", ".join(langs) if isinstance(langs, list) and langs else str(langs or "")
    return f"{gate_type} — {langs_str}"


def prose(evidence: dict, key: str, fallback: str = "") -> str:
    """Return explanation if present, else quote, else fallback."""
    return evidence.get(f"{key}_explanation") or evidence.get(key) or fallback


def write_files(data: dict):
    jd_id = data["jd_id"]
    jd_text = data.pop("jd_text", "")
    source_url = data.get("source_url", "")
    evidence = data.get("evidence", {})

    out_dir = JD_DATA_DIR / jd_id
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── jd_archive.md ──────────────────────────────────────────────────────
    archive_md = f"**URL:** {source_url}\n\n{jd_text}"
    (out_dir / "jd_archive.md").write_text(archive_md, encoding="utf-8")

    # ── jd.md ──────────────────────────────────────────────────────────────
    salary_line = ""
    if data.get("salary_min") and data.get("salary_max"):
        currency = data.get("salary_currency", "")
        lo = f"{int(data['salary_min']):,}"
        hi = f"{int(data['salary_max']):,}"
        salary_line = f"\n**Salary:** {lo}–{hi} {currency}"

    collab_teams = evidence.get("collaboration_width", "none identified")
    interview = data.get("interview_stages")
    interview_str = str(interview) if interview is not None else "Not stated in JD"
    lang_gate = fmt_language_gate(data, evidence)
    loss_aversion = evidence.get("loss_aversion", "No loss aversion framing detected.")
    ats_kws = evidence.get("ats_keywords", [])
    ats_kw_lines = "\n".join(f"- {kw}" for kw in ats_kws) if ats_kws else "- (none extracted)"

    jd_md = f"""# {data['role']} — {data['company']}

**URL:** {source_url}
**Location:** {data.get('job_location', '')}
**Date Posted:** {jd_id[:10]}{salary_line}

---

{jd_text}

---

## Layer B — Behavioural Analysis

*3-run LLM consistency check: `../state_of_analytics_engineering/jd_traces/{jd_id}.md` (generated by `classify_jds.py`, may not exist yet)*

**velocity_vs_rigour:** {data.get('velocity_vs_rigour')} — {prose(evidence, 'velocity_vs_rigour')}

**domain_risk:** {data.get('domain_risk')} — {prose(evidence, 'domain_risk')}

**collaboration_width:** {data.get('collaboration_width')} — named teams: {collab_teams}

**data_team_maturity:** {data.get('data_team_maturity')} — {prose(evidence, 'data_team_maturity')}

**jd_authorship:** {data.get('jd_authorship')} — {prose(evidence, 'jd_authorship')}

**stakeholder_orientation:** {data.get('stakeholder_orientation')} — {prose(evidence, 'stakeholder_orientation')}

**autonomy_level:** {data.get('autonomy_level')} — {prose(evidence, 'autonomy_level')}

**greenfield_vs_fix:** {data.get('greenfield_vs_fix')} — {prose(evidence, 'greenfield_vs_fix')}

**urgency:** {data.get('urgency')} — {prose(evidence, 'urgency', 'No urgency signals present.')}

**language_gate:** {lang_gate}

**interview_stages:** {interview_str}

**ats_platform:** {data.get('ats_platform', 'unknown')}

**ats_job_id:** {data.get('ats_job_id') or 'Not identifiable'}

**loss_aversion:** {loss_aversion}

**ATS keywords:**
{ats_kw_lines}
"""
    (out_dir / "jd.md").write_text(jd_md.strip() + "\n", encoding="utf-8")

    # ── {jd_id}.json ───────────────────────────────────────────────────────
    record = {k: data.get(k) for k in JSON_FIELD_ORDER if k in data or k == "evidence"}
    record["evidence"] = evidence
    # Ensure bool fields are actual booleans
    for f in BOOL_FIELDS:
        v = record.get(f)
        if isinstance(v, str):
            record[f] = v.lower() == "true"
    json_path = out_dir / f"{jd_id}.json"
    json_path.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Written to jd_data/{jd_id}/")
    print(f"  jd_archive.md")
    print(f"  jd.md")
    print(f"  {jd_id}.json")


def main():
    raw = sys.stdin.read().strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"ERROR: invalid JSON on stdin — {e}", file=sys.stderr)
        sys.exit(1)
    write_files(data)


if __name__ == "__main__":
    main()
